model:
  name: "microsoft/DialoGPT-medium"
  max_length: 512
  temperature: 0.7
  top_p: 0.9
  top_k: 50

training:
  batch_size: 4
  learning_rate: 5e-5
  epochs: 3
  warmup_steps: 100
  max_grad_norm: 1.0
  weight_decay: 0.01

data:
  max_context_length: 2048
  overlap: 200
  train_split: 0.8
  val_split: 0.2

paths:
  data_dir: "data/"
  models_dir: "data/models/"
  plots_dir: "plots/"
  cache_dir: ".cache/"

visualization:
  default_theme: "plotly_white"
  color_palette: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"]
  figure_size: [800, 600]

api:
  max_requests_per_minute: 60
  timeout: 30
